version: '3.9'
services:
  # order_service:
  #   build: ./order_service
  #   image: order_service
  #   depends_on:
  #     mysql:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #     rabbitmq:
  #       condition: service_healthy
  #   ports:
  #     - "8081:8000"

  #   environment:
  #     - REDIS_ADDR=redis:6379

  #     - MYSQL_USER=root
  #     - MYSQL_PASSWORD=root_c0d92de67d7634d2acc285670141d25e
  #     - MYSQL_HOST=mysql:3306

  #     - DEPOSITE_SERVICE_URL=http://deposite_service:8000/deposites

  #     - KUCOIN_API_KEY=62bc3b693ff6b60001b19442
  #     - KUCOIN_API_SECRET=c5a12b89-aae2-4028-8810-8332fbf30d72
  #     - KUCOIN_API_PASSPHRASE=77103121

  #     - RABBITMQ_USER=user_0
  #     - RABBITMQ_PASS=user_0a3l3b3qmqnb83rj
  #     - RABBITMQ_HOST=rabbitmq:5672

  deposite_service:
    build: ./deposite_service
    image: deposite_service
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "8080:8000"

    environment:
      - REDIS_ADDR=redis:6379

      - MYSQL_USER=root
      - MYSQL_PASSWORD=root_c0d92de67d7634d2acc285670141d25e
      - MYSQL_HOST=mysql:3306

      - KUCOIN_API_KEY=62bc3b693ff6b60001b19442
      - KUCOIN_API_SECRET=c5a12b89-aae2-4028-8810-8332fbf30d72
      - KUCOIN_API_PASSPHRASE=77103121

      - RABBITMQ_USER=user_0
      - RABBITMQ_PASS=user_0a3l3b3qmqnb83rj
      - RABBITMQ_HOST=rabbitmq:5672

  mysql:
    image: mysql:latest
    volumes:
      - ./deposite_service/db/1.sql:/docker-entrypoint-initdb.d/deposit_service.sql
      - ./order_service/db/1.sql:/docker-entrypoint-initdb.d/order_service.sql
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_c0d92de67d7634d2acc285670141d25e
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "-uroot",
          "-proot_c0d92de67d7634d2acc285670141d25e",
          "ping",
          "-h",
          "localhost"
        ]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:latest

    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis:/data
    # ports:
    #   - "6379:6379"

    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 20
  rabbitmq:
    image: rabbitmq
    # ports:
    #   - "5672:5672"
    #   - "15672:15672"

    environment:
      - RABBITMQ_DEFAULT_USER=user_0
      - RABBITMQ_DEFAULT_PASS=user_0a3l3b3qmqnb83rj

    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 5s
      retries: 20
