openapi: 3.0.0
info:
  title: Exchange Provider Main Api
  version: 1.0.0
servers:
  - url: http://31.220.92.97:80
paths:
  /pairs:
    post:
      tags:
        - MetaData
      summary: pairs list
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                currentPage:
                  type: integer
                pageSize:
                  type: integer
              example:
                currentPage: 1
                pageSize: 10
              required:
                - currentPage
                - pageSize
      parameters:
        - name: x-api-key
          in: header
          required: true
          schema:
            type: string
          example: api_key_ZEsZWKlSuYrjodxqGFVNERxaqIcNwmYW
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}

  /estimate:
    post:
      tags:
        - MetaData
      summary: estimate amountOut
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                input:
                  type: object
                  properties:
                    symbol:
                      type: string
                      example: "USDT"
                    standard:
                      type: string
                      example: "ERC20"
                    network:
                      type: string
                      example: "POLYGON"
                output:
                  type: object
                  properties:
                    symbol:
                      type: string
                      example: "BTC"
                    standard:
                      type: string
                      example: "BTC"
                    network:
                      type: string
                      example: "BITCOIN"

                amountIn:
                  type: number
                lp:
                  type: number
              example:
                amountIn: 10
              required:
                - input
                - output
                - amountIn
      parameters:
        - name: x-api-key
          in: header
          required: true
          schema:
            type: string
          example: api_key_ZEsZWKlSuYrjodxqGFVNERxaqIcNwmYW
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}

  /orders/get:
    post:
      tags:
        - MetaData
      summary: orders history
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                currentPage:
                  type: integer
                pageSize:
                  type: integer
              example:
                currentPage: 1
                pageSize: 10
              required:
                - currentPage
                - pageSize
      parameters:
        - name: x-api-key
          in: header
          required: true
          schema:
            type: string
          example: api_key_ZEsZWKlSuYrjodxqGFVNERxaqIcNwmYW
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}

  /orders/create:
    post:
      tags:
        - 1- create order
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                input:
                  type: object
                  properties:
                    symbol:
                      type: string
                      example: "USDT"
                    standard:
                      type: string
                      example: "ERC20"
                    network:
                      type: string
                      example: "POLYGON"
                output:
                  type: object
                  properties:
                    symbol:
                      type: string
                      example: "BTC"
                    standard:
                      type: string
                      example: "BTC"
                    network:
                      type: string
                      example: "BITCOIN"

                sender:
                  type: object
                  properties:
                    address:
                      type: string
                      example: "0xbBe66c60B52726392ADa50f8047E18872c31cd95"
                    tag:
                      type: string
                receiver:
                  type: object
                  properties:
                    address:
                      type: string
                      example: "bc1q74pglzk0u3qyvxjvmtx5pjzuh2wraskegw7emu"
                    tag:
                      type: string
                amountIn:
                  type: number
                lp:
                  type: number

              example:
                userId: usr-6414af95cc2c0f9e249be8d6
                amountIn: 3.4
                lp: 3
              required:
                - userId
                - input
                - output
                - sender
                - receiver
                - amountIn

      parameters:
        - name: x-api-key
          in: header
          required: true
          schema:
            type: string
          example: api_key_ZEsZWKlSuYrjodxqGFVNERxaqIcNwmYW
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}

  /orders/{orderId}/{step}:
    get:
      tags:
        - 2- get steps (MultiStep)
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
            example: ord-6414c15d0a0fa5707e24bf45
        - name: step
          in: path
          required: true
          schema:
            type: integer
            example: 2
        - name: x-api-key
          in: header
          required: true
          schema:
            type: string
          example: api_key_ZEsZWKlSuYrjodxqGFVNERxaqIcNwmYW
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}

  /orders/set_tx_id:
    post:
      tags:
        - 3- set txId (SingleStep)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                orderId:
                  type: string
                txId:
                  type: string
              example:
                orderId: ord-6414c15d0a0fa5707e24bf45
                txId: >-
                  0xe18c3d74e043c8ebc653e22ccfd8d4612d6754d8dd6b5ea3430d7338a33c6c7e
              required:
                - orderId
                - txId
      parameters:
        - name: x-api-key
          in: header
          required: true
          schema:
            type: string
          example: api_key_ZEsZWKlSuYrjodxqGFVNERxaqIcNwmYW
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
